### ISSUE TITLE
0.7.4 Unknown Error (0.6.0 worked fine)

### ISSUE THREAD

**Issue by DAE51D** [natekspencer/hacs-oasis_mini#17]
`0.6.0` was working fine. `0.7.4` updated today and now see errors and verified IP address in app and HA.

![image](https://github.com/user-attachments/assets/c8d8c870-49b7-4562-8d3d-5f8531786d6b)

```
This error originated from a custom integration.

Logger: custom_components.oasis_mini
Source: custom_components/oasis_mini/__init__.py:39
integration: Oasis Mini (documentation, issues)
First occurred: 11:14:26 AM (317 occurrences)
Last logged: 5:58:49 PM

Couldn't read from the Oasis Mini after 1 attempts
Traceback (most recent call last):
  File "/config/custom_components/oasis_mini/coordinator.py", line 51, in _async_update_data
    await self.device.async_get_playlist_details()
  File "/config/custom_components/oasis_mini/pyoasismini/__init__.py", line 379, in async_get_playlist_details
    tracks = await self.async_cloud_get_tracks(self.playlist)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/oasis_mini/pyoasismini/__init__.py", line 358, in async_cloud_get_tracks
    track_details = response.get("data", [])
                    ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 312, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/oasis_mini/coordinator.py", line 54, in _async_update_data
    raise UpdateFailed(
homeassistant.helpers.update_coordinator.UpdateFailed: Couldn't read from the Oasis Mini after 1 attempts

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/oasis_mini/__init__.py", line 39, in async_setup_entry
    await coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 284, in async_config_entry_first_refresh
    raise ex
homeassistant.exceptions.ConfigEntryNotReady: Couldn't read from the Oasis Mini after 1 attempts
```

**Comment by natekspencer** [comment]
With the issues everyone seems to be having today and the acknowledgment from Kinetic Oasis, it's been a little tougher to try to debug today, but can you give 0.7.5 a shot? And if you are still seeing errors, please enable debug logs and post those. Thanks!

**Comment by DAE51D** [comment]
`0.7.5` seems to work for me 👍🏼 
![image](https://github.com/user-attachments/assets/95caf0d4-9fd2-40eb-b0a5-4a7c3b4eae86)
